### ISSUE TITLE
"The file cannot be reopened" when used with Django imagekit

### ISSUE THREAD

**Issue by mgalgs** [etianen/django-s3-storage#33] opened 2016-10-04 04:35 UTC
I'm using django-s3-storage along with [django-imagekit](https://github.com/matthewwithanm/django-imagekit), but there seems to be a problem with the way django-s3-storage opens files.  It's easy to reproduce, and I have a full django app and repro instructions for the issue, here: https://github.com/mgalgs/iktest

I was a bit thrown off for a while because django-s3-storage isn't anywhere in the stack trace of the erroneous situation, but @scottmx81 figured out that the test app works fine with django-storages, **or** by monkey-patching `pilkit.open_image` like so:

``` python
from pilkit.lib import Image
from pilkit import utils


def open_image(target):
    try:
        target.seek(0)
        return Image.open(target)
    except ValueError:
        return Image.open(target.storage.open(target.name))

utils.open_image = open_image
```

With django-storages no monkey-patch is required...

/cc @scottmx81

**Comment by etianen** [comment] 2016-10-04 10:11
Thanks for the report?

Could you give me the full stack trace?

Do you get the same error using filesystemstorage?

**Comment by etianen** [comment] 2016-10-04 10:46
Okay, I don't think that this is an error with django-s3-storage.

Check out the source of your error, here:

https://github.com/django/django/blob/master/django/core/files/base.py#L131

Some part of your code is closing the file, then reopening it, which is not supported by in-memory files. Look for a `with` statement or `close` being called on the file somewhere, or maybe an option to have the pilkit not close the file when it's done.

I think it's working with django-storages because they seem to stream stuff to disk for all file operations, while django-s3-storage uses memory until the file exceeds 10MB. Files on disk can be reopened, hence the difference in behaviour. django-s3-storage will perform better for lots of small files (such as use as a staticfiles storage), but you have to be careful about not closing files until you're done with them.

**Comment by scottmx81** [comment] 2016-10-14 01:04
@etianen thanks, you are right that there is a ```close``` being called on the file somewhere. The django-imagekit library that we are using generates thumbnails from a source image. After generating each thumbnail, it closes the source image, and then opens it again when generating the next thumbnail. I have confirmed that by commenting out the line of code where the source image is closed, the test app referenced by @mgalgs will work correctly.

The problem is that it does not seem like calling close on an image field, and then opening it again, is a bug in the other code. This does work without problem when using filesystemstorage.

Is there any possibility that support for reopening a file could be included in django-s3-storage? I understand that it is the Django File class where the error is coming from, and that it is using os.path.exists to check for the file in the server filesystem, and not through the Django storage system that it was originally opened with. But what about if instead of returning the File class from  Django when the file is opened through django-s3-storages, it returned a subclass of File that was aware of S3, and tried opening itself again through django-s3-storages, instead of using ```os.path.exists``` and Python built-in ```open``` function?

**Comment by etianen** [comment] 2016-10-17 09:47
You make a very good point. I'll look into this next week.

**Comment by etianen** [comment] 2016-10-17 09:47
OR, I'll take a pull request! :)

**Comment by etianen** [comment] 2016-10-31 13:22
Apologies for the delay, I was massively bogged down with other work.

S3 files can now be re-opened. Of course, better still to keep them open, as it's more efficient, but at least being inefficient works now! :)

**Closed** 2016-10-31 13:21 UTC
Labels: enhancement

**Comment by mgalgs** [comment] 2016-11-02 03:55
Fix confirmed! Thank you!!!

If you'd like, feel free to reap [this](https://www.bountysource.com/issues/29153575-error-when-trying-to-access-width-height-after-url-in-templates) small bounty :).

**Comment by etianen** [comment] 2016-11-02 10:33
Heh, no worries, closing an issue is it's own reward.

If nobody steps forth to claim it, maybe throw the money at a worthy charity.
